### PR TITLE
Added sc v4 to peerDependency.

### PR DESCRIPTION
**Pull request by alansouzati**
probably the easiest PR review of your entire life.

### CODE REVIEW

**Comment by mbasso** [comment]
Hi @alansouzati,
thank you for the PR 😄 
I haven't tried this library with styled-components@4 yet, does it work fine without changes?
Do you think that we need to update the tests with the v4?

**Comment by alansouzati** [comment]
I'm using styled-components v4 and it works without issues.

I think adding a test with v4 is a good idea, but I'm not sure how to install both v3 and v4 at the same time.

**Comment by alansouzati** [comment]
potentially you would want a test for every version you declare in your peerDependency.

**Comment by mbasso** [comment]
yeah, that makes sense.
Maybe we should check if it worth to create a test suite for each version or if we should just update the tests to the latest one. I think that we certainly have to update the test suite to the v4 right now. What do you think about it?

**Comment by alansouzati** [comment]
Sure I can try to update it, I will try to squeeze time for this soon

**Comment by mbasso** [comment]
Awesome! Thank you 😄

**Comment by alansouzati** [comment]
yeah I definitely under estimated this. I gave it a go and there were a bunch of tests failing:

1) Component name assertion now always returns `StyledComponent`. So I get a bunch of Expected `Foo` got `StyledComponent`. I feel this is due to `withComponent`, they are deprecating this API and I'm not sure how to support both `withComponent` and `as` in your testing library.
2) `injectGlobalStyle` has been replaced with `createGlobalStyle` and the existing code you have to extract the CSS is not able to get that global style anymore.
3) Keyframes also are failing with an `interpolation` complaint when you create a `RegExp` based on the keyframe value. I'm not sure how to solve that either.

That said, I will leave this quiet for now, unless you have some pointers that can help me move faster.

**Comment by alansouzati** [comment]
I don't think anything is broken with your `stylesheet` utils, since the jest v4 does exactly the same thing:

https://github.com/styled-components/jest-styled-components/blob/7103ceab03ef8e6b8a6ecd4e9be8a2aa249e898d/src/utils.js

except that they use an AST.

I think previously `injectGlobalStyle` would not require you to mount the component and now `createGlobalStyle` does require a mount. But then I'm not sure if we should mount inside `toHaveGlobalStyle` similarly as you do in `toHaveComponent`. Although I don't think shallow mount would work there.

**Comment by mbasso** [comment]
> 1. Component name assertion now always returns StyledComponent.

With the new `as` API, I think that we don't need a matcher like `toHaveComponent`, maybe we can just test the prop with a normal snapshot. What do you think?

> 3. Keyframes also are failing with an interpolation complaint when you create a RegExp based on the keyframe value. I'm not sure how to solve that either.

The problem is that [_"keyframes no longer returns an animation name, instead it returns an object which has method .getName() for the purpose of getting the animation name"_](https://github.com/styled-components/styled-components/releases/tag/v4.0.0). So we have to update the matcher and use the `.getName()`.
We also have to consider this: "_Keyframes is now implemented in a "lazy" manner: its styles will be injected with the render phase of components using them._". Maybe we have to mount a component inside the matcher...

> I think previously injectGlobalStyle would not require you to mount the component and now createGlobalStyle does require a mount. But then I'm not sure if we should mount inside toHaveGlobalStyle similarly as you do in toHaveComponent. Although I don't think shallow mount would work there.

I think that in this case we should not mount inside the matcher. In this way we can offer much flexibility. Global styles can now depends on some props, users can now insert them conditionally inside the render function and we need the `ThemeProvider` to make them work.
What do you think about it?

About the v2/v3 and v4 support, I think that I can create a new branch that holds the current release, maybe we can call it `v2_and_v3` or something like this.
The `master` branch will support instead the v4 of the `styled-components` library, so we have to release a major update.
In order to do that we need to update dependencies, tests, broken matchers and the `README` file with the new APIs, example and reference to the v2/v3 version.

Do you think that this should be the right solution?
Let me know if I can help you with the developments, also with code contribution.
If all is fine I'll rename this PR to underline that is a work in progress for the v4 support.

**Comment by alansouzati** [comment]
Thanks for the detailed response.

I like your inclination to create a separate branch. I would also recommend releasing a v1 and v2.

Right now you are `0.5.0` so it will be hard to introduce breaking changes between 0.5.0 and 0.6.0.

I would release 1.0.0 with v2 and v3 support. and release v2 with v4 support where the API is tuned for it.

I would love you to take over this since I have some other open source projects that I maintain and I'm pretty overloaded at the moment.

**Comment by mbasso** [comment]
Sure 😄  I'll publish the v1.0.0 and create a separate branch for the v4. I'll create also a work in progress PR to track the progress.
I'll publish an alpha version when it will be ready, so you can try it out in your project before publishing the v2.0.0, is it ok?

**Comment by alansouzati** [comment]
sure thing.

**Comment by mbasso** [comment]
closed in favor of #16

**Pull request closed without merging**
